name: 'AV Sync'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
jobs:
  sync:
    environment: sync
    name: 'AV Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    env:
      DOWNLOAD_URL: https://www.geodienste.ch/downloads/interlis/av/SH
      FILE_NAME: av_SH_lv95.zip

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    # Update references
    - name: Git checkout master
      run: |
        git checkout master
    # Download current AV state
    - name: Download AV
      run: |
        curl -X GET -o /tmp/av_SH_lv95.zip $DOWNLOAD_URL/$FILE_NAME
        ls -ls /tmp/$FILE_NAME
    - name: Unzip AV
      run: |
        unzip /tmp/$FILE_NAME '*.itf' -o -d ./
    - name: Commit changes
      run: |
        git add .
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git commit . -m 'update AV on $(date --iso-8601=seconds) from $DOWNLOAD_URL/$FILE_NAME'
        git push
